// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace BHDemo.Data
{

    // Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class User
    {
        public int Id { get; set; } // ID (Primary key)
        public string Username { get; set; } // Username (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime EditedDate { get; set; } // EditedDate
        public string EditedBy { get; set; } // EditedBy (length: 50)

        public User()
        {
            CreatedDate = System.DateTime.Now;
            EditedDate = System.DateTime.Now;
        }
    }

}
// </auto-generated>
